<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1I0JH3D" failures="1" tests="2" name="Test" time="33.707" errors="0" timestamp="2024-12-08T18:48:55 IST">
  <testcase classname="testCases.TC02_SignIn" name="verify_sign_in" time="5.942"/>
  <testcase classname="testCases.TC01_CreateAnAccountTest" name="verify_account_registration" time="5.359">
    <failure type="java.lang.AssertionError" message="expected [Thank you for registering with Main Website Store.] but found [There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account.]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for registering with Main Website Store.] but found [There is already an account with this email address. If you are sure that it is your email address, click here to get your password and access your account.]
at testCases.TC01_CreateAnAccountTest.verify_account_registration(TC01_CreateAnAccountTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
</testsuite> <!-- Test -->
